import { ConstructorClientOptions, NetworkParameters } from '.';

export default Campaigns;

export interface RetrieveCampaignsParameters {
  section?: string;
  id?: number | number[];
  refinedFilters?: Record<string, string | string[]>;
  numResultsPerPage?: number;
  page?: number;
  offset?: number;
  refinedRecommendationContexts?: RefinedRecommendationContext;
  refinedQueries?: string[];
}

export interface RefinedRecommendationContext {
  pod_id?: string[];
  condition_type?: ('attribute' | 'item' | 'expression')[];
}

export interface RetrieveCampaignParameters {
  id: number;
  section?: string;
}

export interface CreateCampaignParameters extends Record<string, any> {
  name: string;
  section?: string;
  description?: string;
  requestTagName?: RequestTag;
  requestTagValue?: string;
  startTime?: string;
  endTime?: string;
  refinedQueries?: RefinedQuery[];
  refinedFilters?: RefinedFilter[];
  refinedRecommendationContexts?: RecommendationContext[];
  boostRules?: CampaignRuleInput[];
  blacklistRules?: CampaignRuleInput[];
  slotRules?: CampaignRuleInput[];
  contentRules?: CampaignRuleInput[];
  filtersSlotRules?: CampaignRuleInput[];
  whitelistRule?: CampaignRuleInput | null;
  variationSlicingRule?: CampaignRuleInput | null;
  metadataJson?: CampaignMetadata;
}

export interface UpdateCampaignParameters extends Record<string, any> {
  id: number;
  section?: string;
  name?: string;
  description?: string;
  requestTagName?: RequestTag;
  requestTagValue?: string;
  startTime?: string;
  endTime?: string;
  refinedQueries?: RefinedQuery[];
  refinedFilters?: RefinedFilter[];
  refinedRecommendationContexts?: RecommendationContext[];
  boostRules?: CampaignRuleInput[];
  blacklistRules?: CampaignRuleInput[];
  slotRules?: CampaignRuleInput[];
  contentRules?: CampaignRuleInput[];
  filtersSlotRules?: CampaignRuleInput[];
  whitelistRule?: CampaignRuleInput | null;
  variationSlicingRule?: CampaignRuleInput | null;
  metadataJson?: CampaignMetadata;
}

export interface DeleteCampaignParameters {
  id: number;
  section?: string;
}

declare class Campaigns {
  constructor(options: ConstructorClientOptions);

  options: ConstructorClientOptions;

  retrieveCampaigns(
    parameters?: RetrieveCampaignsParameters,
    networkParameters?: NetworkParameters
  ): Promise<CampaignListGetResponse>;

  retrieveCampaign(
    parameters: RetrieveCampaignParameters,
    networkParameters?: NetworkParameters
  ): Promise<CampaignGetResponse>;

  createCampaign(
    parameters: CreateCampaignParameters,
    networkParameters?: NetworkParameters
  ): Promise<CampaignPostResponse>;

  updateCampaign(
    parameters: UpdateCampaignParameters,
    networkParameters?: NetworkParameters
  ): Promise<CampaignPatchResponse>;

  deleteCampaign(
    parameters: DeleteCampaignParameters,
    networkParameters?: NetworkParameters
  ): Promise<void>;
}

export type RequestTag =
  | 'client_ip'
  | 'client_version'
  | 'geo_city'
  | 'geo_country'
  | 'geo_country_iso_code'
  | 'geo_region'
  | 'dt_weekday'
  | 'dt_timeofday'
  | 'user_segment'
  | 'autogenerated_user_segment'
  | 'dynamic_segment';

export interface RefinedQuery {
  query: string;
}

export interface RefinedFilter {
  filter_name: string;
  filter_value: string;
}

export interface RecommendationContext {
  pod_id: string;
  condition: RecommendationContextCondition;
}

export type RecommendationContextCondition =
  | RecommendationContextItemCondition
  | RecommendationContextAttributeCondition
  | RecommendationContextExpressionCondition;

export interface RecommendationContextItemCondition {
  type: 'item';
  item_id?: string;
}

export interface RecommendationContextAttributeCondition {
  type: 'attribute';
  filter_name?: string;
  filter_value?: string;
}

export interface RecommendationContextExpressionCondition {
  type: 'expression';
  expression: Record<string, string[]>;
}

export interface CampaignRule extends Record<string, any> {
  id: number;
  rule: Record<string, any>;
  rule_type:
    | 'boost'
    | 'blacklist'
    | 'slot'
    | 'content'
    | 'filters_slot'
    | 'whitelist'
    | 'variation_slicing';
  request_tag_name?: RequestTag;
  request_tag_value?: string;
  active?: boolean;
  start_time?: string;
  end_time?: string;
  campaign_id?: number;
  automatically_generated?: boolean;
  created_at?: string;
  updated_at?: string;
}

/* rule definition supplied when creating or modifying a campaign */
export interface CampaignRuleInput extends Record<string, any> {
  rule: Record<string, any>;
  rule_type?:
    | 'boost'
    | 'blacklist'
    | 'slot'
    | 'content'
    | 'filters_slot'
    | 'whitelist'
    | 'variation_slicing';
  request_tag_name?: RequestTag;
  request_tag_value?: string;
  active?: boolean;
  start_time?: string;
  end_time?: string;
  campaign_id?: number;
  automatically_generated?: boolean;
}

export interface CampaignMetadata {
  goal?: string;
  goal_description?: string;
}

export interface Campaign extends Record<string, any> {
  id: number;
  created_at: string;
  updated_at: string;
  name?: string;
  description?: string;
  request_tag_name?: RequestTag;
  request_tag_value?: string;
  start_time?: string;
  end_time?: string;
  refined_queries?: RefinedQuery[];
  refined_filters?: RefinedFilter[];
  refined_recommendation_contexts?: RecommendationContext[];
  boost_rules?: CampaignRule[];
  blacklist_rules?: CampaignRule[];
  slot_rules?: CampaignRule[];
  content_rules?: CampaignRule[];
  filters_slot_rules?: CampaignRule[];
  whitelist_rule?: CampaignRule;
  variation_slicing_rule?: CampaignRule;
  metadata_json?: CampaignMetadata;
}

/* campaigns results returned from server */
export interface CampaignListGetResponse {
  campaigns: Campaign[];
  total_count: number;
}

/* single campaign result returned from server */
export type CampaignGetResponse = Campaign;

/* campaign result returned from server after creation */
export type CampaignPostResponse = Campaign;

/* campaign result returned from server after update */
export type CampaignPatchResponse = Campaign;
