name: Run tests
on:
  pull_request:
    branches:
      - "**"
concurrency:
  group: run-tests-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18.13.0"]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test:parallel
        env:
          TEST_REQUEST_API_KEY: ${{ secrets.TEST_REQUEST_API_KEY }}
          TEST_CATALOG_API_KEY: ${{ secrets.TEST_CATALOG_API_KEY }}
          TEST_API_TOKEN: ${{ secrets.TEST_API_TOKEN }}
          SKIP_NETWORK_TIMEOUT_TESTS: true
